import jsPDF from "jspdf";

export function generatePDF(result) {
  const doc = new jsPDF();

  // ===== HEADER =====
  doc.setFillColor(79, 70, 229); // Indigo
  doc.rect(0, 0, 210, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("Digital Twin Academic Report", 105, 20, { align: "center" });

  // ===== BODY TEXT =====
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);

  let y = 45;
  doc.text(`Overall Score: ${result.score}`, 20, y);

  y += 12;
  doc.text(`Study Hours: ${result.metrics.studyHours} hrs/day`, 20, y);
  y += 10;
  doc.text(`Sleep Hours: ${result.metrics.sleepHours} hrs/night`, 20, y);
  y += 10;
  doc.text(`Attendance: ${result.metrics.attendance}%`, 20, y);
  y += 10;
  doc.text(`Stress Level: ${result.metrics.stressLevel}`, 20, y);
  y += 10;
  doc.text(`Screen Time: ${result.metrics.screenTime} hrs`, 20, y);

  // ===== HABIT IMPACT BARS =====
y += 15;
doc.setFontSize(14);
doc.text("Habit Impact Breakdown", 20, y);

y += 8;

const drawBar = (label, value, max, color) => {
  doc.setFontSize(11);
  doc.text(label, 20, y);

  doc.setFillColor(220, 220, 220);
  doc.rect(20, y + 3, 100, 6, "F");

  doc.setFillColor(...color);
  doc.rect(20, y + 3, (value / max) * 100, 6, "F");

  y += 12;
};

drawBar("Study", result.metrics.studyHours, 10, [79, 70, 229]);
drawBar("Sleep", result.metrics.sleepHours, 10, [16, 185, 129]);
drawBar("Attendance", result.metrics.attendance, 100, [245, 158, 11]);
drawBar("Stress (Lower is Better)", 5 - result.metrics.stressLevel, 5, [239, 68, 68]);


  // ===== FOOTER =====
  doc.setFontSize(10);
  doc.text("Generated by DigiTwin • Academic Performance Predictor", 105, 285, {
    align: "center",
  });

  doc.save("Digital_Twin_Report.pdf");
}
